### ISSUE TITLE
Google Login

### ISSUE THREAD

**Issue by hariskhawja** [JFSS-iNNOVATE/iNNOVATE_website#6]
Overview: Connect and complete integration of the Google login API to the website.

Tools Required: Google API, JavaScript, React.js

Details: Integrate the Google login API, such that users are able to login to the website with their Google accounts to use the forum. Google login should be smooth and follow the usual process. The website must also identify and remember that the user is logged in when on the website.

**Comment by Edison611** [comment]
Completed
